{ config, lib, pkgs, unstable, ... }:

{
  imports = [ 
               ./gtk
               ./emacs
	];
  home = { 
    packages = with pkgs; [ 
      nftables
      lutris
      ferium
      brave
      unstable.ladybird
      zoom-us
      discord
      teams-for-linux
      rclone
      android-file-transfer
      thunderbird
      onlyoffice-bin
      deja-dup
      redshift
      networkmanagerapplet
      simple-scan
      mate.mate-tweak
      dconf2nix
      gnupg
      xclip
      hydra-check
      xdotool
      git-crypt
      nix-prefetch-git
      qutebrowser
      mpv
      whatsapp-for-linux
      cmus
      gccgo13
      go
      android-tools
      xclip
      gccgo13
      krita
      virtiofsd
      mediainfo
      audacity
      gimp
      weechat
      obs-studio
      direnv
      nodePackages.bash-language-server
      freecad
      kicad
      keymapp
      mesa-demos
      protonvpn-gui
      jdk17
      wineWowPackages.staging 
      winetricks 
    ];
  };
}
